// Zentrale Vokabeldatenbank für alle Spiele (Lektionen Salve bis 6)
// Präzise typisiert für flexible didaktische Filterungen.

const globalVocabularyPool = [
    // ================= VERBEN =================
    { latin: "esse", type: "verb", middle: "sum", gram_clue: "1. Pers. Sg.: sum", gram_class: "unregelmäßiges Verb", meaning: "sein; es gibt" },
    { latin: "clāmāre", type: "verb", middle: "clāmō", gram_clue: "1. Pers. Sg.: clāmō", gram_class: "a-Konjugation", meaning: "rufen, laut rufen" },
    { latin: "venīre", type: "verb", middle: "veniō", gram_clue: "1. Pers. Sg.: veniō", gram_class: "i-Konjugation", meaning: "kommen" },
    { latin: "labōrāre", type: "verb", middle: "labōrō", gram_clue: "1. Pers. Sg.: labōrō", gram_class: "a-Konjugation", meaning: "arbeiten, sich bemühen" },
    { latin: "lūdere", type: "verb", middle: "lūdō", gram_clue: "1. Pers. Sg.: lūdō", gram_class: "konsonantische Konjugation", meaning: "spielen" },
    { latin: "cantāre", type: "verb", middle: "cantō", gram_clue: "1. Pers. Sg.: cantō", gram_class: "a-Konjugation", meaning: "singen" },
    { latin: "gaudēre", type: "verb", middle: "gaudeō", gram_clue: "1. Pers. Sg.: gaudeō", gram_class: "e-Konjugation", meaning: "sich freuen" },
    { latin: "currere", type: "verb", middle: "currō", gram_clue: "1. Pers. Sg.: currō", gram_class: "konsonantische Konjugation", meaning: "laufen, rennen" },
    { latin: "exspectāre", type: "verb", middle: "exspectō", gram_clue: "1. Pers. Sg.: exspectō", gram_class: "a-Konjugation", meaning: "erwarten, warten auf" },
    { latin: "audīre", type: "verb", middle: "audiō", gram_clue: "1. Pers. Sg.: audiō", gram_class: "i-Konjugation", meaning: "hören, zuhören" },
    { latin: "rogāre", type: "verb", middle: "rogō", gram_clue: "1. Pers. Sg.: rogō", gram_class: "a-Konjugation", meaning: "fragen, bitten" },
    { latin: "quaerere", type: "verb", middle: "quaerō", gram_clue: "1. Pers. Sg.: quaerō", gram_class: "konsonantische Konjugation", meaning: "suchen, fragen" },
    { latin: "vidēre", type: "verb", middle: "videō", gram_clue: "1. Pers. Sg.: videō", gram_class: "e-Konjugation", meaning: "sehen" },
    { latin: "intrāre", type: "verb", middle: "intrō", gram_clue: "1. Pers. Sg.: intrō", gram_class: "a-Konjugation", meaning: "betreten, eintreten" },
    { latin: "rīdēre", type: "verb", middle: "rīdeō", gram_clue: "1. Pers. Sg.: rīdeō", gram_class: "e-Konjugation", meaning: "lachen, auslachen" },
    { latin: "tenēre", type: "verb", middle: "teneō", gram_clue: "1. Pers. Sg.: teneō", gram_class: "e-Konjugation", meaning: "halten, festhalten" },
    { latin: "amāre", type: "verb", middle: "amō", gram_clue: "1. Pers. Sg.: amō", gram_class: "a-Konjugation", meaning: "lieben, mögen" },
    { latin: "respondēre", type: "verb", middle: "respondeō", gram_clue: "1. Pers. Sg.: respondeō", gram_class: "e-Konjugation", meaning: "antworten" },
    { latin: "dēbēre", type: "verb", middle: "dēbeō", gram_clue: "1. Pers. Sg.: dēbeō", gram_class: "e-Konjugation", meaning: "müssen" },
    { latin: "explēre", type: "verb", middle: "expleō", gram_clue: "1. Pers. Sg.: expleō", gram_class: "e-Konjugation", meaning: "erfüllen" },
    { latin: "dīcere", type: "verb", middle: "dīcō", gram_clue: "1. Pers. Sg.: dīcō", gram_class: "konsonantische Konjugation", meaning: "sagen" },
    { latin: "placēre", type: "verb", middle: "placeō", gram_clue: "1. Pers. Sg.: placeō", gram_class: "e-Konjugation", meaning: "gefallen, Spaß machen" },
    { latin: "neglegere", type: "verb", middle: "neglegō", gram_clue: "1. Pers. Sg.: neglegō", gram_class: "konsonantische Konjugation", meaning: "vernachlässigen, nicht beachten" },
    { latin: "pergere", type: "verb", middle: "pergō", gram_clue: "1. Pers. Sg.: pergō", gram_class: "konsonantische Konjugation", meaning: "etw. weiter tun, fortsetzen" },
    { latin: "dēlectāre", type: "verb", middle: "dēlectō", gram_clue: "1. Pers. Sg.: dēlectō", gram_class: "a-Konjugation", meaning: "erfreuen" },
    { latin: "alere", type: "verb", middle: "alō", gram_clue: "1. Pers. Sg.: alō", gram_class: "konsonantische Konjugation", meaning: "nähren, ernähren" },
    { latin: "salūtāre", type: "verb", middle: "salūtō", gram_clue: "1. Pers. Sg.: salūtō", gram_class: "a-Konjugation", meaning: "grüßen" },
    { latin: "parāre", type: "verb", middle: "parō", gram_clue: "1. Pers. Sg.: parō", gram_class: "a-Konjugation", meaning: "vorbereiten, zubereiten" },
    { latin: "adiuvāre", type: "verb", middle: "adiuvō", gram_clue: "1. Pers. Sg.: adiuvō", gram_class: "a-Konjugation", meaning: "unterstützen" },
    { latin: "properāre", type: "verb", middle: "properō", gram_clue: "1. Pers. Sg.: properō", gram_class: "a-Konjugation", meaning: "eilen, sich beeilen" },
    { latin: "instruere", type: "verb", middle: "instruō", gram_clue: "1. Pers. Sg.: instruō", gram_class: "konsonantische Konjugation", meaning: "anweisen, unterrichten" },
    { latin: "agere", type: "verb", middle: "agō", gram_clue: "1. Pers. Sg.: agō", gram_class: "konsonantische Konjugation", meaning: "tun, handeln" },
    { latin: "caedere", type: "verb", middle: "caedō", gram_clue: "1. Pers. Sg.: caedō", gram_class: "konsonantische Konjugation", meaning: "töten, schlachten" },
    { latin: "servāre", type: "verb", middle: "servō", gram_clue: "1. Pers. Sg.: servō", gram_class: "a-Konjugation", meaning: "retten" },
    { latin: "obsecrāre", type: "verb", middle: "obsecrō", gram_clue: "1. Pers. Sg.: obsecrō", gram_class: "a-Konjugation", meaning: "anflehen" },
    { latin: "dūcere", type: "verb", middle: "dūcō", gram_clue: "1. Pers. Sg.: dūcō", gram_class: "konsonantische Konjugation", meaning: "führen" },
    { latin: "vocāre", type: "verb", middle: "vocō", gram_clue: "1. Pers. Sg.: vocō", gram_class: "a-Konjugation", meaning: "rufen" },
    { latin: "sedēre", type: "verb", middle: "sedeō", gram_clue: "1. Pers. Sg.: sedeō", gram_class: "e-Konjugation", meaning: "sitzen" },
    { latin: "cōnsīdere", type: "verb", middle: "cōnsīdō", gram_clue: "1. Pers. Sg.: cōnsīdō", gram_class: "konsonantische Konjugation", meaning: "sich hinsetzen" },
    { latin: "discere", type: "verb", middle: "discō", gram_clue: "1. Pers. Sg.: discō", gram_class: "konsonantische Konjugation", meaning: "lernen" },
    { latin: "scrībere", type: "verb", middle: "scrībō", gram_clue: "1. Pers. Sg.: scrībō", gram_class: "konsonantische Konjugation", meaning: "schreiben" },
    { latin: "legere", type: "verb", middle: "legō", gram_clue: "1. Pers. Sg.: legō", gram_class: "konsonantische Konjugation", meaning: "lesen" },
    { latin: "tacēre", type: "verb", middle: "taceō", gram_clue: "1. Pers. Sg.: taceō", gram_class: "e-Konjugation", meaning: "schweigen" },
    { latin: "monēre", type: "verb", middle: "moneō", gram_clue: "1. Pers. Sg.: moneō", gram_class: "e-Konjugation", meaning: "ermahnend, mahnen" },
    { latin: "mōnstrāre", type: "verb", middle: "mōnstrō", gram_clue: "1. Pers. Sg.: mōnstrō", gram_class: "a-Konjugation", meaning: "zeigen" },
    { latin: "pūnīre", type: "verb", middle: "pūniō", gram_clue: "1. Pers. Sg.: pūniō", gram_class: "i-Konjugation", meaning: "bestrafen" },
    { latin: "portāre", type: "verb", middle: "portō", gram_clue: "1. Pers. Sg.: portō", gram_class: "a-Konjugation", meaning: "tragen" },
    { latin: "docēre", type: "verb", middle: "doceō", gram_clue: "1. Pers. Sg.: doceō", gram_class: "e-Konjugation", meaning: "unterrichten, lehren" },
    { latin: "cōnspicere", type: "verb", middle: "cōnspiciō", gram_clue: "1. Pers. Sg.: cōnspiciō", gram_class: "gemischte Konjugation", meaning: "erblicken, sehen" },
    { latin: "accēdere", type: "verb", middle: "accēdō", gram_clue: "1. Pers. Sg.: accēdō", gram_class: "konsonantische Konjugation", meaning: "sich nähern, herbeikommen" },
    { latin: "facere", type: "verb", middle: "faciō", gram_clue: "1. Pers. Sg.: faciō", gram_class: "gemischte Konjugation", meaning: "machen, tun" },
    { latin: "cupere", type: "verb", middle: "cupiō", gram_clue: "1. Pers. Sg.: cupiō", gram_class: "gemischte Konjugation", meaning: "wollen, wünschen" },
    { latin: "praebēre", type: "verb", middle: "praebeō", gram_clue: "1. Pers. Sg.: praebeō", gram_class: "e-Konjugation", meaning: "bieten, gewähren" },
    { latin: "capere", type: "verb", middle: "capiō", gram_clue: "1. Pers. Sg.: capiō", gram_class: "gemischte Konjugation", meaning: "fangen, ergreifen" },
    { latin: "accūsāre", type: "verb", middle: "accūsō", gram_clue: "1. Pers. Sg.: accūsō", gram_class: "a-Konjugation", meaning: "beschuldigen" },
    { latin: "incipere", type: "verb", middle: "incipiō", gram_clue: "1. Pers. Sg.: incipiō", gram_class: "gemischte Konjugation", meaning: "anfangen, beginnen" },
    { latin: "fugere", type: "verb", middle: "fugiō", gram_clue: "1. Pers. Sg.: fugiō", gram_class: "gemischte Konjugation", meaning: "fliehen (vor), entkommen" },
    { latin: "reddere", type: "verb", middle: "reddō", gram_clue: "1. Pers. Sg.: reddō", gram_class: "konsonantische Konjugation", meaning: "zurückgeben" },
    { latin: "manēre", type: "verb", middle: "maneō", gram_clue: "1. Pers. Sg.: maneō", gram_class: "e-Konjugation", meaning: "bleiben, erwarten" },
    { latin: "vincere", type: "verb", middle: "vincō", gram_clue: "1. Pers. Sg.: vincō", gram_class: "konsonantische Konjugation", meaning: "siegen, besiegen" },
    { latin: "canere", type: "verb", middle: "canō", gram_clue: "1. Pers. Sg.: canō", gram_class: "konsonantische Konjugation", meaning: "ertönen, singen, spielen" },
    { latin: "dare", type: "verb", middle: "dō", gram_clue: "1. Pers. Sg.: dō", gram_class: "a-Konjugation", meaning: "geben" },
    { latin: "incitāre", type: "verb", middle: "incitō", gram_clue: "1. Pers. Sg.: incitō", gram_class: "a-Konjugation", meaning: "antreiben, anfeuern" },
    { latin: "arcēre", type: "verb", middle: "arceō", gram_clue: "1. Pers. Sg.: arceō", gram_class: "e-Konjugation", meaning: "abwehren, fernhalten" },
    { latin: "surgere", type: "verb", middle: "surgō", gram_clue: "1. Pers. Sg.: surgō", gram_class: "konsonantische Konjugation", meaning: "aufstehen, sich erheben" },
    { latin: "praestāre", type: "verb", middle: "praestō", gram_clue: "1. Pers. Sg.: praestō", gram_class: "a-Konjugation", meaning: "sich hervortun, übertreffen, besser sein" },
    { latin: "crēscere", type: "verb", middle: "crēscō", gram_clue: "1. Pers. Sg.: crēscō", gram_class: "konsonantische Konjugation", meaning: "wachsen" },
    { latin: "tangere", type: "verb", middle: "tangō", gram_clue: "1. Pers. Sg.: tangō", gram_class: "konsonantische Konjugation", meaning: "berühren" },
    { latin: "spectāre", type: "verb", middle: "spectō", gram_clue: "1. Pers. Sg.: spectō", gram_class: "a-Konjugation", meaning: "anschauen, betrachten, sehen" },

    // ================= SUBSTANTIVE =================
    { latin: "pater", type: "noun", middle: "patris m.", gram_clue: "Genitiv: patris, m.", gram_class: "konsonantische Deklination", meaning: "der Vater" },
    { latin: "māter", type: "noun", middle: "mātris f.", gram_clue: "Genitiv: mātris, f.", gram_class: "konsonantische Deklination", meaning: "die Mutter" },
    { latin: "fīlius", type: "noun", middle: "fīliī m.", gram_clue: "Genitiv: fīliī, m.", gram_class: "o-Deklination", meaning: "der Sohn" },
    { latin: "fīlia", type: "noun", middle: "fīliae f.", gram_clue: "Genitiv: fīliae, f.", gram_class: "a-Deklination", meaning: "die Tochter" },
    { latin: "avus", type: "noun", middle: "avī m.", gram_clue: "Genitiv: avī, m.", gram_class: "o-Deklination", meaning: "der Großvater" },
    { latin: "servus", type: "noun", middle: "servī m.", gram_clue: "Genitiv: servī, m.", gram_class: "o-Deklination", meaning: "der Sklave" },
    { latin: "serva", type: "noun", middle: "servae f.", gram_clue: "Genitiv: servae, f.", gram_class: "a-Deklination", meaning: "die Sklavin" },
    { latin: "catella", type: "noun", middle: "catellae f.", gram_clue: "Genitiv: catellae, f.", gram_class: "a-Deklination", meaning: "das Hündchen" },
    { latin: "dominus", type: "noun", middle: "dominī m.", gram_clue: "Genitiv: dominī, m.", gram_class: "o-Deklination", meaning: "der Herr, der Hausherr" },
    { latin: "domina", type: "noun", middle: "dominae f.", gram_clue: "Genitiv: dominae, f.", gram_class: "a-Deklination", meaning: "die Hausherrin" },
    { latin: "familia", type: "noun", middle: "familiae f.", gram_clue: "Genitiv: familiae, f.", gram_class: "a-Deklination", meaning: "die Hausgemeinschaft, die Familie" },
    { latin: "clāmor", type: "noun", middle: "clāmōris m.", gram_clue: "Genitiv: clāmōris, m.", gram_class: "konsonantische Deklination", meaning: "der Lärm, das Geschrei, der Ruf" },
    { latin: "soror", type: "noun", middle: "sorōris f.", gram_clue: "Genitiv: sorōris, f.", gram_class: "konsonantische Deklination", meaning: "die Schwester" },
    { latin: "puer", type: "noun", middle: "puerī m.", gram_clue: "Genitiv: puerī, m.", gram_class: "o-Deklination", meaning: "das Kid, der Junge" },
    { latin: "frāter", type: "noun", middle: "frātris m.", gram_clue: "Genitiv: frātris, m.", gram_class: "konsonantische Deklination", meaning: "der Bruder" },
    { latin: "culīna", type: "noun", middle: "culīnae f.", gram_clue: "Genitiv: culīnae, f.", gram_class: "a-Deklination", meaning: "die Küche" },
    { latin: "līberī", type: "noun", middle: "līberōrum m. Pl.", gram_clue: "Genitiv Pl.: līberōrum, m.", gram_class: "o-Deklination", meaning: "die Kinder" },
    { latin: "vir", type: "noun", middle: "virī m.", gram_clue: "Genitiv: virī, m.", gram_class: "o-Deklination", meaning: "der Mann" },
    { latin: "ātrium", type: "noun", middle: "ātriī n.", gram_clue: "Genitiv: ātriī, n.", gram_class: "o-Deklination", meaning: "das Atrium" },
    { latin: "ōtium", type: "noun", middle: "ōtiī n.", gram_clue: "Genitiv: ōtiī, n.", gram_class: "o-Deklination", meaning: "die Ruhe, die Freizeit" },
    { latin: "parentēs", type: "noun", middle: "parentum m. Pl.", gram_clue: "Genitiv Pl.: parentum, m.", gram_class: "konsonantische Deklination", meaning: "die Eltern" },
    { latin: "peristȳlium", type: "noun", middle: "peristȳliī n.", gram_clue: "Genitiv: peristȳliī, n.", gram_class: "o-Deklination", meaning: "das Peristyl" },
    { latin: "officium", type: "noun", middle: "officiī n.", gram_clue: "Genitiv: officiī, n.", gram_class: "o-Deklination", meaning: "die Pflicht" },
    { latin: "labor", type: "noun", middle: "labōris m.", gram_clue: "Genitiv: labōris, m.", gram_class: "konsonantische Deklination", meaning: "die Mühe, die Arbeit" },
    { latin: "equus", type: "noun", middle: "equī m.", gram_clue: "Genitiv: equī, m.", gram_class: "o-Deklination", meaning: "das Pferd" },
    { latin: "canis", type: "noun", middle: "canis m.", gram_clue: "Genitiv: canis, m.", gram_class: "konsonantische Deklination", meaning: "der Hund" },
    { latin: "bōs", type: "noun", middle: "bovis m.", gram_clue: "Genitiv: bovis, m.", gram_class: "konsonantische Deklination", meaning: "das Rind, der Ochse" },
    { latin: "villa", type: "noun", middle: "villae f.", gram_clue: "Genitiv: villae, f.", gram_class: "a-Deklination", meaning: "das Landhaus, das Landgut" },
    { latin: "uxor", type: "noun", middle: "uxōris f.", gram_clue: "Genitiv: uxōris, f.", gram_class: "konsonantische Deklination", meaning: "die Ehefrau" },
    { latin: "cēna", type: "noun", middle: "cēnae f.", gram_clue: "Genitiv: cēnae, f.", gram_class: "a-Deklination", meaning: "die Mahlzeit, das Essen" },
    { latin: "hortus", type: "noun", middle: "hortī m.", gram_clue: "Genitiv: hortī, m.", gram_class: "o-Deklination", meaning: "der Garten" },
    { latin: "schola", type: "noun", middle: "scholae f.", gram_clue: "Genitiv: scholae, f.", gram_class: "a-Deklination", meaning: "die Schule" },
    { latin: "magister", type: "noun", middle: "magistrī m.", gram_clue: "Genitiv: magistrī, m.", gram_class: "o-Deklination", meaning: "der Lehrer" },
    { latin: "tabula", type: "noun", middle: "tabulae f.", gram_clue: "Genitiv: tabulae, f.", gram_class: "a-Deklination", meaning: "das Wachstäfelchen" },
    { latin: "discipulus", type: "noun", middle: "discipulī m.", gram_clue: "Genitiv: discipulī, m.", gram_class: "o-Deklination", meaning: "der Schüler" },
    { latin: "discipula", type: "noun", middle: "discipulae f.", gram_clue: "Genitiv: discipulae, f.", gram_class: "a-Deklination", meaning: "die Schülerin" },
    { latin: "forum", type: "noun", middle: "forī n.", gram_clue: "Genitiv: forī, n.", gram_class: "o-Deklination", meaning: "das Forum, der Marktplatz" },
    { latin: "monumentum", type: "noun", middle: "monumentī n.", gram_clue: "Genitiv: monumentī, n.", gram_class: "o-Deklination", meaning: "das Denkmal" },
    { latin: "statua", type: "noun", middle: "statuae f.", gram_clue: "Genitiv: statuae, f.", gram_class: "a-Deklination", meaning: "die Statue" },
    { latin: "homō", type: "noun", middle: "hominis m.", gram_clue: "Genitiv: hominis, m.", gram_class: "konsonantische Deklination", meaning: "der Mensch, der Mann" },
    { latin: "amicus", type: "noun", middle: "amicī m.", gram_clue: "Genitiv: amicī, m.", gram_class: "o-Deklination", meaning: "der Freund" },
    { latin: "amica", type: "noun", middle: "amicae f.", gram_clue: "Genitiv: amicae, f.", gram_class: "a-Deklination", meaning: "die Freundin" },
    { latin: "fūr", type: "noun", middle: "fūris m.", gram_clue: "Genitiv: fūris, m.", gram_class: "konsonantische Deklination", meaning: "der Dieb" },
    { latin: "dōnum", type: "noun", middle: "dōnī n.", gram_clue: "Genitiv: dōnī, n.", gram_class: "o-Deklination", meaning: "das Geschenk" },
    { latin: "mors", type: "noun", middle: "mortis f.", gram_clue: "Genitiv: mortis, f.", gram_class: "konsonantische Deklination", meaning: "der Tod" },
    { latin: "Circus Maximus", type: "noun", middle: "Circī Maximī m.", gram_clue: "Genitiv: Circī Maximī, m.", gram_class: "o-Deklination", meaning: "der Circus Maximus" },
    { latin: "spectātor", type: "noun", middle: "spectātōris m.", gram_clue: "Genitiv: spectātōris, m.", gram_class: "konsonantische Deklination", meaning: "der Zuschauer" },
    { latin: "gaudium", type: "noun", middle: "gaudiī n.", gram_clue: "Genitiv: gaudiī, n.", gram_class: "o-Deklination", meaning: "die Freude" },
    { latin: "agitātor", type: "noun", middle: "agitātōris m.", gram_clue: "Genitiv: agitātōris, m.", gram_class: "konsonantische Deklination", meaning: "der Wagenlenker" },
    { latin: "tunica", type: "noun", middle: "tunicae f.", gram_clue: "Genitiv: tunicae, f.", gram_class: "a-Deklination", meaning: "die Tunika" },
    { latin: "verbum", type: "noun", middle: "verbī n.", gram_clue: "Genitiv: verbī, n.", gram_class: "o-Deklination", meaning: "das Wort" },
    { latin: "signum", type: "noun", middle: "signī n.", gram_clue: "Genitiv: signī, n.", gram_class: "o-Deklination", meaning: "das Zeichen" },
    { latin: "imperātor", type: "noun", middle: "imperātōris m.", gram_clue: "Genitiv: imperātōris, m.", gram_class: "konsonantische Deklination", meaning: "der Kaiser" },
    { latin: "tuba", type: "noun", middle: "tubae f.", gram_clue: "Genitiv: tubae, f.", gram_class: "a-Deklination", meaning: "die Trompete" },
    { latin: "pecūnia", type: "noun", middle: "pecūniae f.", gram_clue: "Genitiv: pecūniae, f.", gram_class: "a-Deklination", meaning: "das Geld" },
    { latin: "audītōr", type: "noun", middle: "audītōris m.", gram_clue: "Genitiv: audītōris, m.", gram_class: "konsonantische Deklination", meaning: "der Zuhörer" },
    { latin: "victor", type: "noun", middle: "victōris m.", gram_clue: "Genitiv: victōris, m.", gram_class: "konsonantische Deklination", meaning: "der Sieger" },

    // ================= ADJEKTIVE =================
    { latin: "Rōmānus, -a, -um", type: "adjective", middle: "a-/o-Deklination", gram_clue: "Adjektiv (o-/a-)", gram_class: "a-/o-Deklination", meaning: "römisch" },
    { latin: "multi, -ae, -a", type: "adjective", middle: "a-/o-Deklination", gram_clue: "Adjektiv (Plural)", gram_class: "a-/o-Deklination", meaning: "viele" },
    { latin: "parvus, -a, -um", type: "adjective", middle: "a-/o-Deklination", gram_clue: "Adjektiv (o-/a-)", gram_class: "a-/o-Deklination", meaning: "klein" },
    { latin: "magnus, -a, -um", type: "adjective", middle: "a-/o-Deklination", gram_clue: "Adjektiv (o-/a-)", gram_class: "a-/o-Deklination", meaning: "groß, bedeutend" },
    { latin: "pulcher, pulchra, pulchrum", type: "adjective", middle: "a-/o-Deklination", gram_clue: "Adjektiv (er-Form)", gram_class: "a-/o-Deklination", meaning: "schön, hübsch" },
    { latin: "īrātus, -a, -um", type: "adjective", middle: "a-/o-Deklination", gram_clue: "Adjektiv (o-/a-)", gram_class: "a-/o-Deklination", meaning: "zornig, wütend" },
    { latin: "malus, -a, -um", type: "adjective", middle: "a-/o-Deklination", gram_clue: "Adjektiv (o-/a-)", gram_class: "a-/o-Deklination", meaning: "schlecht, böse" },
    { latin: "aureus, -a, -um", type: "adjective", middle: "a-/o-Deklination", gram_clue: "Adjektiv (o-/a-)", gram_class: "a-/o-Deklination", meaning: "golden, aus Gold" },
    { latin: "bonus, -a, -um", type: "adjective", middle: "a-/o-Deklination", gram_clue: "Adjektiv (o-/a-)", gram_class: "a-/o-Deklination", meaning: "gut" },
    { latin: "rēctus, -a, -um", type: "adjective", middle: "a-/o-Deklination", gram_clue: "Adjektiv (o-/a-)", gram_class: "a-/o-Deklination", meaning: "gerade, richtig, ehrlich" },
    { latin: "miser, misera, miserum", type: "adjective", middle: "a-/o-Deklination", gram_clue: "Adjektiv (er-Form)", gram_class: "a-/o-Deklination", meaning: "arm, unglücklich, elend" },
    { latin: "tūtus, -a, -um", type: "adjective", middle: "a-/o-Deklination", gram_clue: "Adjektiv (o-/a-)", gram_class: "a-/o-Deklination", meaning: "sicher, geschützt" },
    { latin: "praeclārus, -a, -um", type: "adjective", middle: "a-/o-Deklination", gram_clue: "Adjektiv (o-/a-)", gram_class: "a-/o-Deklination", meaning: "berühmt, ausgezeichnet" },
    { latin: "meus, -a, -um", type: "adjective", middle: "a-/o-Deklination", gram_clue: "Poss.-Pron.", gram_class: "a-/o-Deklination", meaning: "mein(e)" },
    { latin: "tuus, -a, -um", type: "adjective", middle: "a-/o-Deklination", gram_clue: "Poss.-Pron.", gram_class: "a-/o-Deklination", meaning: "dein(e)" },
    { latin: "noster, nostra, nostrum", type: "adjective", middle: "a-/o-Deklination", gram_clue: "Poss.-Pron. (er-Form)", gram_class: "a-/o-Deklination", meaning: "unser(e)" },
    { latin: "vester, vestra, vestrum", type: "adjective", middle: "a-/o-Deklination", gram_clue: "Poss.-Pron. (er-Form)", gram_class: "a-/o-Deklination", meaning: "euer, eure" },
    { latin: "suus, -a, -um", type: "adjective", middle: "a-/o-Deklination", gram_clue: "refl. Poss.-Pron.", gram_class: "a-/o-Deklination", meaning: "sein(e), ihr(e)" },
    { latin: "cūnctī, -ae, -a", type: "adjective", middle: "a-/o-Deklination", gram_clue: "Adjektiv (Plural)", gram_class: "a-/o-Deklination", meaning: "alle" },
    { latin: "cēterī, -ae, -a", type: "adjective", middle: "a-/o-Deklination", gram_clue: "Adjektiv (Plural)", gram_class: "a-/o-Deklination", meaning: "die übrigen" },
    { latin: "mortuus, -a, -um", type: "adjective", middle: "a-/o-Deklination", gram_clue: "Adjektiv (o-/a-)", gram_class: "a-/o-Deklination", meaning: "tot" },

    // ================= DYNAMISCH TYPISIERTE PARTIKELN =================
    { latin: "salvē!", type: "other", middle: "Ausruf", gram_clue: "", gram_class: "", meaning: "Sei begrüßt!" },
    { latin: "hic", type: "adverb", middle: "Adv.", gram_clue: "", gram_class: "", meaning: "hier" },
    { latin: "et", type: "conjunction", middle: "Konj.", gram_clue: "", gram_class: "", meaning: "und" },
    { latin: "nam", type: "conjunction", middle: "Konj.", gram_clue: "", gram_class: "", meaning: "denn" },
    { latin: "hodiē", type: "adverb", middle: "Adv.", gram_clue: "", gram_class: "", meaning: "heute" },
    { latin: "subitō", type: "adverb", middle: "Adv.", gram_clue: "", gram_class: "", meaning: "plötzlich" },
    { latin: "quid?", type: "pronoun", middle: "Pronomen", gram_clue: "", gram_class: "", meaning: "was?" },
    { latin: "nōn", type: "other", middle: "Negation", gram_clue: "", gram_class: "", meaning: "nicht" },
    { latin: "sed", type: "conjunction", middle: "Konj.", gram_clue: "", gram_class: "", meaning: "aber, sondern" },
    { latin: "ubi?", type: "adverb", middle: "Adv.", gram_clue: "", gram_class: "", meaning: "wo?" },
    { latin: "ecce!", type: "other", middle: "Ausruf", gram_clue: "+ Nom./Akk.", gram_class: "", meaning: "sieh(e) da!, sieh(e)!" },
    { latin: "tum", type: "adverb", middle: "Adv.", gram_clue: "", gram_class: "", meaning: "dann, darauf, da (zeitlich)" },
    { latin: "ibi", type: "adverb", middle: "Adv.", gram_clue: "", gram_class: "", meaning: "dort" },
    { latin: "nunc", type: "adverb", middle: "Adv.", gram_clue: "", gram_class: "", meaning: "nun, jetzt" },
    { latin: "etiam", type: "conjunction", middle: "Konj.", gram_clue: "", gram_class: "", meaning: "auch, sogar" },
    { latin: "iterum", type: "adverb", middle: "Adv.", gram_clue: "", gram_class: "", meaning: "wieder" },
    { latin: "statim", type: "adverb", middle: "Adv.", gram_clue: "", gram_class: "", meaning: "sofort" },
    { latin: "itaque", type: "adverb", middle: "Adv.", gram_clue: "", gram_class: "", meaning: "deshalb" },
    { latin: "adhūc", type: "adverb", middle: "Adv.", gram_clue: "", gram_class: "", meaning: "bis jetzt, noch" },
    { latin: "illīc", type: "adverb", middle: "Adv.", gram_clue: "", gram_class: "", meaning: "dort" },
    { latin: "cūr?", type: "adverb", middle: "Adv.", gram_clue: "", gram_class: "", meaning: "warum?" },
    { latin: "semper", type: "adverb", middle: "Adv.", gram_clue: "", gram_class: "", meaning: "immer" },
    { latin: "ego / mē", type: "pronoun", middle: "Pers.-Pron.", gram_clue: "Nom. / Akk.", gram_class: "", meaning: "ich / mich" },
    { latin: "tū / tē", type: "pronoun", middle: "Pers.-Pron.", gram_clue: "Nom. / Akk.", gram_class: "", meaning: "du / dich" },
    { latin: "nōs / nōs", type: "pronoun", middle: "Pers.-Pron.", gram_clue: "Nom. / Akk.", gram_class: "", meaning: "wir / uns" },
    { latin: "vōs / vōs", type: "pronoun", middle: "Pers.-Pron.", gram_clue: "Nom. / Akk.", gram_class: "", meaning: "ihr / euch" },
    { latin: "paulō post", type: "adverb", middle: "Phrase", gram_clue: "", gram_class: "", meaning: "ein wenig später" },
    { latin: "iam", type: "adverb", middle: "Adv.", gram_clue: "", gram_class: "", meaning: "schon, gleich, jetzt" },
    { latin: "in", type: "preposition", middle: "Präp. + Akk.", gram_clue: "Richtungsangabe", gram_class: "", meaning: "in (... hinein)" },
    { latin: "ante", type: "preposition", middle: "Präp. + Akk.", gram_clue: "", gram_class: "", meaning: "vor" },
    { latin: "ad", type: "preposition", middle: "Präp. + Akk.", gram_clue: "", gram_class: "", meaning: "zu (... hin), an" },
    { latin: "bene", type: "adverb", middle: "Adv.", gram_clue: "", gram_class: "", meaning: "gut" },
    { latin: "certē", type: "adverb", middle: "Adv.", gram_clue: "", gram_class: "", meaning: "sicher, gewiss" },
    { latin: "per", type: "preposition", middle: "Präp. + Akk.", gram_clue: "", gram_class: "", meaning: "über, durch" },
    { latin: "autem", type: "conjunction", middle: "Konj.", gram_clue: "nachgestellt", gram_class: "", meaning: "aber, jedoch" },
    { latin: "igitur", type: "adverb", middle: "Adv.", gram_clue: "", gram_class: "", meaning: "also" },
    { latin: "-que", type: "conjunction", middle: "Konj.", gram_clue: "angehängt", gram_class: "", meaning: "und" },
    { latin: "-ne?", type: "other", middle: "Fragepartikel", gram_clue: "angehängt", gram_class: "", meaning: "leitet eine Frage ein" },
    { latin: "nōnne?", type: "other", middle: "Fragepartikel", gram_clue: "", gram_class: "", meaning: "etwa nicht?, doch wohl?" },
    { latin: "num?", type: "other", middle: "Fragepartikel", gram_clue: "", gram_class: "", meaning: "etwa?, denn?" },
    { latin: "atque", type: "conjunction", middle: "Konj.", gram_clue: "", gram_class: "", meaning: "und" },
    { latin: "nōlī / nōlīte", type: "other", middle: "Verbotspartikel", gram_clue: "+ Infinitiv", gram_class: "", meaning: "leitet ein Verbot ein (Sg. / Pl.)" },
    { latin: "ita", type: "adverb", middle: "Adv.", gram_clue: "", gram_class: "", meaning: "so" },
    { latin: "posteā", type: "adverb", middle: "Adv.", gram_clue: "", gram_class: "", meaning: "danach, später" },
    { latin: "quis?", type: "pronoun", middle: "Pronomen", gram_clue: "", gram_class: "", meaning: "wer?" },
    { latin: "domum", type: "adverb", middle: "Adv.", gram_clue: "Richtungsangabe", gram_class: "", meaning: "nach Hause" },
    { latin: "ergō", type: "adverb", middle: "Adv.", gram_clue: "", gram_class: "", meaning: "deshalb, also" },
    { latin: "prope", type: "preposition", middle: "Präp. + Akk.", gram_clue: "", gram_class: "", meaning: "nahe bei" },
    { latin: "tam", type: "adverb", middle: "Adv.", gram_clue: "", gram_class: "", meaning: "so" },
    { latin: "aut", type: "conjunction", middle: "Konj.", gram_clue: "", gram_class: "", meaning: "oder" },
    { latin: "profectō", type: "adverb", middle: "Adv.", gram_clue: "", gram_class: "", meaning: "tatsächlich" },
    { latin: "tandem", type: "adverb", middle: "Adv.", gram_clue: "", gram_class: "", meaning: "schließlich, endlich" },
    { latin: "eius", type: "pronoun", middle: "Poss.-Pron.", gram_clue: "nicht-refl. Sg.", gram_class: "", meaning: "sein(e), ihr(e), dessen, deren" },
    { latin: "eōrum / eārum / eōrum", type: "pronoun", middle: "Poss.-Pron.", gram_clue: "nicht-refl. Pl.", gram_class: "", meaning: "deren, ihr(e)" },
    { latin: "nōn iam", type: "adverb", middle: "Phrase", gram_clue: "", gram_class: "", meaning: "nicht mehr" },
    { latin: "inter", type: "preposition", middle: "Präp. + Akk.", gram_clue: "", gram_class: "", meaning: "zwischen, unter" },
    { latin: "simul", type: "adverb", middle: "Adv.", gram_clue: "", gram_class: "", meaning: "gleichzeitig, zugleich" },
    { latin: "ferē", type: "adverb", middle: "Adv.", gram_clue: "", gram_class: "", meaning: "fast, etwa" },
    { latin: "sē", type: "pronoun", middle: "Refl.-Pron.", gram_clue: "Akkusativ", gram_class: "", meaning: "sich" }
];
